Fix test compilation on non-macOS Darwin platforms (#2817)
### Motivation

Some tests were making use of `Task.sleep(for:)` which isn't present on older platforms.

```
/workspace/Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift:505:32: error: 'sleep(for:tolerance:clock:)' is only available in tvOS 16.0 or newer
                     try await Task.sleep(for: .milliseconds(1))
```

### Modifications

Update tests to use `Task.sleep(nanoseconds:)` via `TimeAmount.nanoseconds` instead, which is available on those platforms.

### Result

Can build tests on older platforms.